# Load images to IBM Cloud Object Storage

#### Note : JSON files with the URLs were uploaded to IBM Watson Studio before this was run.

In [1]:
import multiprocessing

import os

import json

import random

from io import BytesIO

import requests

from tqdm import tqdm

from PIL import Image

In [2]:
# @hidden_cell
# The following code contains the credentials for a file in your IBM Cloud Object Storage.
# You might want to remove those credentials before you share your notebook.
credentials = {
    'IBM_API_KEY_ID': 'TfcndpWGnoQ64X9Bk626qYXaNZ5NW1W5rGN1OWw_260q',
    'IAM_SERVICE_ID': 'iam-ServiceId-d807c055-f3d5-44aa-b3f1-23b4930f6eea',
    'ENDPOINT': 'https://s3-api.us-geo.objectstorage.service.networklayer.com',
    'IBM_AUTH_ENDPOINT': 'https://iam.ng.bluemix.net/oidc/token',
    'BUCKET': 'imaterialistkaggle4bf0864d4c5048939f8fce50969fe17b'
}

In [3]:
from ibm_botocore.client import Config
import ibm_boto3

cos = ibm_boto3.client(service_name='s3',
    ibm_api_key_id=credentials['IBM_API_KEY_ID'],
    ibm_service_instance_id=credentials['IAM_SERVICE_ID'],
    ibm_auth_endpoint=credentials['IBM_AUTH_ENDPOINT'],
    config=Config(signature_version='oauth'),
    endpoint_url=credentials['ENDPOINT'])

In [4]:
import sys
import types
import pandas as pd

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share your notebook.
client_1cf5112183814bc7a2e594147e0b46c2 = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='TfcndpWGnoQ64X9Bk626qYXaNZ5NW1W5rGN1OWw_260q',
    ibm_auth_endpoint="https://iam.ng.bluemix.net/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3-api.us-geo.objectstorage.service.networklayer.com')

body = client_1cf5112183814bc7a2e594147e0b46c2.get_object(Bucket='imaterialistkaggle4bf0864d4c5048939f8fce50969fe17b',Key='validation.json')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object 

if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

# Since JSON data can be semi-structured and contain additional metadata, it is possible that you might face an error during data loading.
# Please read the documentation of 'pandas.read_json()' and 'pandas.io.json.json_normalize' to learn more about the possibilities to adjust the data loading.
# pandas documentation: http://pandas.pydata.org/pandas-docs/stable/io.html#io-json-reader
# and http://pandas.pydata.org/pandas-docs/stable/generated/pandas.io.json.json_normalize.html

headers = {

    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.146 Safari/537.36',

}
val_json = pd.read_json(body, orient='values')
val_json.head()

annotations  \
0   {'image_id': 1, 'label_id': 38}   
1   {'image_id': 2, 'label_id': 63}   
2   {'image_id': 3, 'label_id': 33}   
3  {'image_id': 4, 'label_id': 126}   
4   {'image_id': 5, 'label_id': 18}   

                                              images  
0  {'url': ['http://www.ghs.net/public/images/fb/...  
1  {'url': ['https://img.alicdn.com/imgextra/TB2c...  
2  {'url': ['http://static-news.17house.com/web/n...  
3  {'url': ['http://img000.hc360.cn/g6/M07/CB/88/...  
4  {'url': ['https://img.alicdn.com/imgextra/T1sL...

In [6]:
val_json.tail()

annotations  \
6395   {'image_id': 6396, 'label_id': 16}   
6396  {'image_id': 6397, 'label_id': 112}   
6397   {'image_id': 6398, 'label_id': 88}   
6398   {'image_id': 6399, 'label_id': 62}   
6399  {'image_id': 6400, 'label_id': 123}   

                                                 images  
6395  {'url': ['https://img10.360buyimg.com/imgzone/...  
6396  {'url': ['https://img.alicdn.com/imgextra/TB2G...  
6397  {'url': ['https://img14.360buyimg.com/imgzone/...  
6398  {'url': ['https://img.alicdn.com/imgextra/TB2F...  
6399  {'url': ['http://imgsrc.baidu.com/image/c0%3Ds...

In [5]:
val_size = val_json.shape[0]
print(val_size)

6400


In [6]:
body = client_1cf5112183814bc7a2e594147e0b46c2.get_object(Bucket='imaterialistkaggle4bf0864d4c5048939f8fce50969fe17b',Key='train.json')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object 

if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

# Since JSON data can be semi-structured and contain additional metadata, it is possible that you might face an error during data loading.
# Please read the documentation of 'pandas.read_json()' and 'pandas.io.json.json_normalize' to learn more about the possibilities to adjust the data loading.
# pandas documentation: http://pandas.pydata.org/pandas-docs/stable/io.html#io-json-reader
# and http://pandas.pydata.org/pandas-docs/stable/generated/pandas.io.json.json_normalize.html

train_json = pd.read_json(body, orient='values')
train_json.head()

annotations  \
0  {'image_id': 1, 'label_id': 5}   
1  {'image_id': 2, 'label_id': 5}   
2  {'image_id': 3, 'label_id': 5}   
3  {'image_id': 4, 'label_id': 5}   
4  {'image_id': 5, 'label_id': 5}   

                                              images  
0  {'url': ['https://img13.360buyimg.com/imgzone/...  
1  {'url': ['http://www.tengdakeli.cn/350/timg01/...  
2  {'url': ['https://img13.360buyimg.com/imgzone/...  
3  {'url': ['http://img4.tbcdn.cn/tfscom/i1/28554...  
4  {'url': ['http://a.vpimg4.com/upload/merchandi...

In [7]:
train_size = train_json.shape[0]
print(train_size)

194828


In [8]:

body = client_1cf5112183814bc7a2e594147e0b46c2.get_object(Bucket='imaterialistkaggle4bf0864d4c5048939f8fce50969fe17b',Key='test.json')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object 

if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

# Since JSON data can be semi-structured and contain additional metadata, it is possible that you might face an error during data loading.
# Please read the documentation of 'pandas.read_json()' and 'pandas.io.json.json_normalize' to learn more about the possibilities to adjust the data loading.
# pandas documentation: http://pandas.pydata.org/pandas-docs/stable/io.html#io-json-reader
# and http://pandas.pydata.org/pandas-docs/stable/generated/pandas.io.json.json_normalize.html

test_json = pd.read_json(body, orient='values')
test_json.head()

images
0  {'url': ['https://img13.360buyimg.com/imgzone/...
1  {'url': ['http://img35.ddimg.cn/79/22/12581687...
2  {'url': ['https://img.alicdn.com/imgextra/TB19...
3  {'url': ['https://img13.360buyimg.com/imgzone/...
4  {'url': ['http://img4.99114.com/group1/M00/7D/...

In [9]:
test_size = test_json.shape[0]
print(test_size)

12800


In [16]:
def download_one(d):

    assert len(d['url']) == 1

    file_name = "{0}{1}.jpg".format(d["prefix"], d["image_id"])
    
    #if file_name in objects:
        #print('Already uploaded to COS')
        #return

    try:

        r = requests.get(d['url'][0], allow_redirects=True, timeout=60,

                         headers=headers)

    except:

        print('error downloading', d['url'][0])

        return

    if r.status_code != 200:

        print('status code != 200', r.status_code, d['url'][0])

        return

    try:

        pil_image = Image.open(BytesIO(r.content))
        pil_image_rgb = pil_image.convert('RGB')
        pil_image_rgb.save(file_name, format='JPEG', quality=90)
        #print('success', d)
        upload_file_cos(credentials, file_name, file_name)
        
        if os.path.isfile(file_name):
            
            os.remove(file_name)

    except Exception as e:
        print(Exception, e)

        #print('error converting data to image', d)


In [28]:
def upload_file_cos(credentials,local_file_name,key): 
    
    cos = ibm_boto3.client(service_name='s3',
    ibm_api_key_id=credentials['IBM_API_KEY_ID'],
    ibm_service_instance_id=credentials['IAM_SERVICE_ID'],
    ibm_auth_endpoint=credentials['IBM_AUTH_ENDPOINT'],
    config=Config(signature_version='oauth'),
    endpoint_url=credentials['ENDPOINT'])

    try:
        
        res=cos.upload_file(Filename=local_file_name, Bucket=credentials['BUCKET'],Key=key)
        
    except Exception as e:
        print(Exception, e)
    else:
        print('File Uploaded')

In [18]:
def download_data(prefix, data):

    print('downloading {}'.format(prefix))

    data = data['images']

    random.shuffle(data)



    pool = multiprocessing.Pool(processes=20)

    for d in data:

        d['prefix'] = prefix


    with tqdm(total=len(data)) as t:

        for _ in pool.imap_unordered(download_one, data):

            t.update(1)
            
files = [

#    ('val', val_json)

    ('test', test_json)

#    ('train', train_json)

]

### ******UPLOAD DATA******

In [ ]:
for prefix, data in files:

    download_data(prefix, data)

#### Check uploaded data

In [10]:
#s3 = ibm_boto3.resource('s3')

s3 = ibm_boto3.resource(service_name='s3',
    ibm_api_key_id=credentials['IBM_API_KEY_ID'],
    ibm_service_instance_id=credentials['IAM_SERVICE_ID'],
    ibm_auth_endpoint=credentials['IBM_AUTH_ENDPOINT'],
    config=Config(signature_version='oauth'),
    endpoint_url=credentials['ENDPOINT'])
bucket = s3.Bucket(credentials['BUCKET'])

In [11]:
objects = bucket.objects

In [53]:
type(objects)

ibm_boto3.resources.collection.s3.Bucket.objectsCollectionManager

In [57]:
train_upload_cnt = 0
val_upload_cnt = 0
for obj in bucket.objects.all():
    key = obj.key
    body = obj.get()['Body'].read()

KeyboardInterrupt: 

In [62]:
# view sample data
image = Image.open(BytesIO(body))
image_rgb = image.convert('RGB')

In [63]:
import matplotlib.pyplot as plt
%matplotlib inline 

plt.imshow(image_rgb)

In [66]:
import numpy as np
img_array =np.asarray(image_rgb)
img_array.shape

(800, 800, 3)

# Finding Missing Data

Should have saved the names of the files that failed download during the download process itself! my bad !

In [12]:
import numpy as np
train_loaded = np.zeros((train_size))
val_loaded = np.zeros((val_size))
test_loaded = np.zeros((test_size))

In [29]:
train_loaded[:5]

array([ 0.,  0.,  0.,  0.,  0.])

In [35]:
#test 
int(''.join(filter(str.isdigit, 'test234567898.jpg')))

234567898

In [13]:
train_upload_cnt = 0
val_upload_cnt = 0
test_upload_cnt = 0
for obj in bucket.objects.all():
    key = obj.key
    #print(key)
    if any(ext in key for ext in ['json', 'ipynb', 'csv']):
        continue  
        
    img_id = int(''.join(filter(str.isdigit, key)))
    
    if key.startswith("train"):
        train_upload_cnt = train_upload_cnt + 1
        train_loaded[img_id - 1] = 1
        continue
    if key.startswith("test"):
        test_upload_cnt = test_upload_cnt + 1
        test_loaded[img_id - 1] = 1
        continue
    if key.startswith("val"):
        val_upload_cnt = val_upload_cnt + 1
        val_loaded[img_id - 1] = 1 

print("train_cnt : ",train_upload_cnt)
print("val_cnt   : ",val_upload_cnt)
print("test_cnt   : ",test_upload_cnt)

train_cnt :  191087
val_cnt   :  6271
test_cnt   :  12481


In [15]:
print("training images missing :" ,train_size - train_upload_cnt)
print("validation images missing :", val_size - val_upload_cnt)
print("test images missing :", test_size - test_upload_cnt)

training images missing : 3741
validation images missing : 129
test images missing : 319


In [16]:
np.where(val_loaded==0)

(array([  60,  120,  187,  366,  458,  464,  465,  512,  756,  847,  856,
         862, 1012, 1057, 1090, 1100, 1126, 1132, 1135, 1157, 1189, 1224,
        1433, 1517, 1519, 1554, 1659, 1663, 1676, 1734, 1834, 1851, 1859,
        1887, 1901, 1960, 1982, 2031, 2076, 2098, 2181, 2211, 2323, 2353,
        2375, 2402, 2423, 2434, 2514, 2517, 2563, 2719, 2781, 2785, 2791,
        2806, 2999, 3022, 3304, 3352, 3363, 3371, 3444, 3528, 3534, 3554,
        3598, 3605, 3629, 3637, 3658, 3723, 3838, 3849, 3888, 3959, 4019,
        4034, 4201, 4290, 4298, 4329, 4370, 4388, 4443, 4526, 4541, 4558,
        4603, 4653, 4751, 4752, 4773, 4840, 4893, 4936, 4994, 5035, 5059,
        5177, 5186, 5346, 5367, 5379, 5398, 5401, 5443, 5502, 5523, 5534,
        5656, 5674, 5717, 5724, 5736, 5799, 5860, 5871, 5877, 6034, 6072,
        6214, 6293, 6302, 6309, 6317, 6356, 6363, 6376]),)

In [20]:
val_missing = np.where(val_loaded==0)[0] + 1

In [38]:
val_missing = np.array(val_missing)

In [39]:
val_missing

array([  61,  121,  188,  367,  459,  465,  466,  513,  757,  848,  857,
        863, 1013, 1058, 1091, 1101, 1127, 1133, 1136, 1158, 1190, 1225,
       1434, 1518, 1520, 1555, 1660, 1664, 1677, 1735, 1835, 1852, 1860,
       1888, 1902, 1961, 1983, 2032, 2077, 2099, 2182, 2212, 2324, 2354,
       2376, 2403, 2424, 2435, 2515, 2518, 2564, 2720, 2782, 2786, 2792,
       2807, 3000, 3023, 3305, 3353, 3364, 3372, 3445, 3529, 3535, 3555,
       3599, 3606, 3630, 3638, 3659, 3724, 3839, 3850, 3889, 3960, 4020,
       4035, 4202, 4291, 4299, 4330, 4371, 4389, 4444, 4527, 4542, 4559,
       4604, 4654, 4752, 4753, 4774, 4841, 4894, 4937, 4995, 5036, 5060,
       5178, 5187, 5347, 5368, 5380, 5399, 5402, 5444, 5503, 5524, 5535,
       5657, 5675, 5718, 5725, 5737, 5800, 5861, 5872, 5878, 6035, 6073,
       6215, 6294, 6303, 6310, 6318, 6357, 6364, 6377])

In [22]:
train_missing = np.where(train_loaded==0)[0] + 1

In [24]:
train_missing[0:5]

array([220, 301, 366, 381, 398])

In [25]:
test_missing = np.where(test_loaded==0)[0] + 1

In [26]:
test_missing[0:5]

array([127, 150, 156, 206, 259])

In [42]:
df = pd.DataFrame(val_missing)
df.to_csv("val_missing.csv")
upload_file_cos(credentials, "val_missing.csv", "val_missing.csv")   

File Uploaded


In [43]:
df = pd.DataFrame(train_missing)
df.to_csv("train_missing.csv")
upload_file_cos(credentials, "train_missing.csv", "train_missing.csv")   

File Uploaded


In [44]:
df = pd.DataFrame(test_missing)
df.to_csv("test_missing.csv")
upload_file_cos(credentials, "test_missing.csv", "test_missing.csv")   

File Uploaded
